from pathlib import Path

path = Path('src/modules/abastecimiento/AbastecimientoModule.jsx')
s = path.read_text(encoding='utf-8')

old = '''  useEffect(()=>{\n    if(raba03InitialLoadDoneRef.current)return;\n    raba03InitialLoadDoneRef.current=true;\n    let cancelled=false;\n    const run=async()=>{\n      let hasCachedRows=false;\n      try{\n        const cached=await readCachedSource(RABA03_DATA_CACHE_KEY);\n        const cachedRows=cached?.value?.ok&&Array.isArray(cached.value.data)?cached.value.data:[];\n        if(cachedRows.length&&!cancelled){\n          hasCachedRows=true;\n          setRows(cachedRows);\n          setLoading(false);\n        }\n      }catch(_){}\n\n      const [remitosResult]=await Promise.allSettled([\n        loadRemitosCompartidos({silent:true}),\n        loadEstadosSolicitudesCompartidos({silent:true})\n      ]);\n      if(cancelled)return;\n      const sharedRemitos=remitosResult.status==="fulfilled"?remitosResult.value:null;\n      await loadRaba03({silent:hasCachedRows,remitosOverride:sharedRemitos});\n      if(!hasCachedRows)setLoading(false);\n    };\n    run().catch(err=>{\n      if(!cancelled){setError(err?.message||String(err));setLoading(false);}\n    });\n    return()=>{cancelled=true;};\n  },[loadRaba03,loadRemitosCompartidos,loadEstadosSolicitudesCompartidos]);'''

new = '''  useEffect(()=>{\n    if(raba03InitialLoadDoneRef.current)return;\n    raba03InitialLoadDoneRef.current=true;\n    let cancelled=false;\n    let completed=false;\n    const run=async()=>{\n      let hasCachedRows=false;\n      try{\n        const cached=await readCachedSource(RABA03_DATA_CACHE_KEY);\n        const cachedPayload=cached?.data||cached?.value||null;\n        const cachedRows=cachedPayload?.ok&&Array.isArray(cachedPayload.data)?cachedPayload.data:[];\n        if(cachedRows.length&&!cancelled){\n          hasCachedRows=true;\n          setRows(cachedRows);\n          setLoading(false);\n        }\n      }catch(_){}\n\n      const [remitosResult]=await Promise.allSettled([\n        loadRemitosCompartidos({silent:true}),\n        loadEstadosSolicitudesCompartidos({silent:true})\n      ]);\n      if(cancelled)return;\n      const sharedRemitos=remitosResult.status==="fulfilled"?remitosResult.value:null;\n      await loadRaba03({silent:hasCachedRows,remitosOverride:sharedRemitos});\n      if(cancelled)return;\n      completed=true;\n      setLoading(false);\n    };\n    run().catch(err=>{\n      if(!cancelled){\n        completed=true;\n        setError(err?.message||String(err));\n        setLoading(false);\n      }\n    });\n    return()=>{\n      cancelled=true;\n      // React.StrictMode monta/desmonta el efecto una vez en desarrollo.\n      // Si la primera ejecución fue cancelada antes de completar, permitir\n      // que el segundo montaje realice nuevamente la carga inicial.\n      if(!completed)raba03InitialLoadDoneRef.current=false;\n    };\n  },[loadRaba03,loadRemitosCompartidos,loadEstadosSolicitudesCompartidos]);'''

if old not in s:
    raise SystemExit('No se encontró el bloque de carga inicial esperado')

s = s.replace(old, new, 1)
path.write_text(s, encoding='utf-8')
