import * as XLSX from "xlsx";
const BUTTON_CLASS="dm-admin-table-export",WRAPPED_ATTR="data-dm-admin-export-ready";
const isAdministrative=()=>String(window.sessionStorage.getItem("dm_role")||"").trim().toUpperCase()==="ADMINISTRATIVO";
function visible(el){if(!el||!el.isConnected)return false;const s=window.getComputedStyle(el);return s.display!=="none"&&s.visibility!=="hidden"&&el.getClientRects().length>0;}
const clean=v=>String(v??"").replace(/\s+/g," ").trim();
function tableTitle(table,index){let node=table.parentElement;for(let d=0;node&&d<5;d++,node=node.parentElement){const h=[...node.querySelectorAll(":scope > h1,:scope > h2,:scope > h3,:scope > h4,:scope > div")].find(el=>el!==table&&visible(el)&&clean(el.textContent).length>0&&clean(el.textContent).length<90);if(h)return clean(h.textContent).replace(/[\\/:*?"<>|]/g," ").slice(0,55);}return`Tabla_${index+1}`;}
function rows(table){const out=[];for(const tr of [...table.querySelectorAll("tr")].filter(visible)){const c=[...tr.children].filter(x=>(x.tagName==="TH"||x.tagName==="TD")&&visible(x));if(c.length)out.push(c.map(x=>clean(x.innerText||x.textContent)));}return out;}
function exportTable(table,index){const data=rows(table);if(!data.length)return;const wb=XLSX.utils.book_new(),ws=XLSX.utils.aoa_to_sheet(data),width=Math.max(...data.map(r=>r.length),1);ws["!cols"]=Array.from({length:width},(_,c)=>({wch:Math.min(45,Math.max(10,...data.map(r=>clean(r[c]).length+2)))}));XLSX.utils.book_append_sheet(wb,ws,"Datos");XLSX.writeFile(wb,`${tableTitle(table,index)||"Tabla"}.xlsx`);}
function decorate(table,index){if(!isAdministrative()||table.getAttribute(WRAPPED_ATTR)==="1")return;table.setAttribute(WRAPPED_ATTR,"1");const host=table.parentElement;if(!host)return;const b=document.createElement("button");b.type="button";b.className=BUTTON_CLASS;b.textContent="↓ Excel";b.title="Descargar exactamente las filas visibles de esta tabla";Object.assign(b.style,{display:"block",margin:"6px 8px 6px auto",padding:"6px 10px",borderRadius:"7px",border:"1px solid rgba(34,197,94,.55)",background:"rgba(34,197,94,.12)",color:"#22c55e",fontSize:"10px",fontWeight:"800",fontFamily:"Inter,Arial,sans-serif",cursor:"pointer",position:"relative",zIndex:"12"});b.addEventListener("click",e=>{e.preventDefault();e.stopPropagation();exportTable(table,index);});host.insertBefore(b,table);}
function scan(){if(isAdministrative())[...document.querySelectorAll(".dm-app-content table")].filter(visible).forEach(decorate);}
export function installAdministrativeTableExports(){if(typeof window==="undefined"||window.__dmAdminTableExportsInstalled)return;window.__dmAdminTableExportsInstalled=true;let raf=0;const schedule=()=>{cancelAnimationFrame(raf);raf=requestAnimationFrame(scan);},observer=new MutationObserver(schedule);observer.observe(document.documentElement,{childList:true,subtree:true,attributes:true,attributeFilter:["style","class"]});window.addEventListener("storage",schedule);document.addEventListener("click",()=>setTimeout(schedule,0),true);schedule();}
