import {requireSupabase} from "./supabaseClient.js";
export const DEFAULT_APPEARANCE=Object.freeze({accent:"red",background:"operations",backgroundCustom:"",backgroundCustomName:"",savedBackgrounds:[],backgroundDim:48,backgroundBlur:0,panelOpacity:55,density:"normal",scale:"normal",sidebar:"remember",reducedMotion:false});
export const APPEARANCE_ACCENTS=Object.freeze([{id:"red",label:"Rojo Delta",hex:"#e8001d"},{id:"blue",label:"Azul",hex:"#3b82f6"},{id:"cyan",label:"Celeste",hex:"#06b6d4"},{id:"green",label:"Verde",hex:"#22c55e"},{id:"orange",label:"Naranja",hex:"#f59e0b"},{id:"purple",label:"Violeta",hex:"#a855f7"}]);
export const APPEARANCE_BACKGROUNDS=Object.freeze([{id:"operations",label:"Cordillera",src:"/img/embedded/home-welcome-b80067ac.jpg",previewFit:"cover"},{id:"login",label:"Delta",src:"/img/embedded/home-inline-0c79147d.png",previewFit:"contain"},{id:"none",label:"Sin imagen",src:"",previewFit:"cover"}]);
const LAST_APPEARANCE_KEY="dm_last_appearance_v1";const storageKey=email=>`dm_appearance_v1:${String(email||"anonymous").trim().toLowerCase()}`;
const safeBackgrounds=value=>(Array.isArray(value)?value:[]).map((x,i)=>({id:String(x?.id||`user:${i}`),label:String(x?.label||x?.name||`Mi fondo ${i+1}`),src:String(x?.src||x?.url||""),thumbnail:String(x?.thumbnail||x?.thumb||x?.src||x?.url||""),fileId:String(x?.fileId||"")})).filter(x=>x.id&&x.src);
export function normalizeAppearance(value={}){const base={...DEFAULT_APPEARANCE,...(value||{})};base.savedBackgrounds=safeBackgrounds(base.savedBackgrounds||base.backgrounds);if(!APPEARANCE_ACCENTS.some(x=>x.id===base.accent))base.accent=DEFAULT_APPEARANCE.accent;const known=APPEARANCE_BACKGROUNDS.some(x=>x.id===base.background)||base.savedBackgrounds.some(x=>x.id===base.background)||base.background==="custom";if(!known)base.background=DEFAULT_APPEARANCE.background;base.backgroundDim=Math.max(0,Math.min(85,Number(base.backgroundDim??48)));base.backgroundBlur=Math.max(0,Math.min(16,Number(base.backgroundBlur??0)));base.panelOpacity=Math.max(35,Math.min(100,Number(base.panelOpacity??55)));if(!["compact","normal","comfortable"].includes(base.density))base.density="normal";if(!["small","normal","large"].includes(base.scale))base.scale="normal";if(!["remember","expanded","compact"].includes(base.sidebar))base.sidebar="remember";base.reducedMotion=Boolean(base.reducedMotion);base.backgroundCustom=String(base.backgroundCustom||"");base.backgroundCustomName=String(base.backgroundCustomName||"");return base;}
export function readLocalAppearance(email){try{return normalizeAppearance(JSON.parse(localStorage.getItem(storageKey(email))||"{}"));}catch(_){return normalizeAppearance();}}export function readLastAppearance(){try{return normalizeAppearance(JSON.parse(localStorage.getItem(LAST_APPEARANCE_KEY)||"{}"));}catch(_){return normalizeAppearance();}}
export function writeLocalAppearance(email,prefs){const normalized=normalizeAppearance(prefs);try{localStorage.setItem(storageKey(email),JSON.stringify(normalized));localStorage.setItem(LAST_APPEARANCE_KEY,JSON.stringify(normalized));window.dispatchEvent(new CustomEvent("dm-appearance-saved",{detail:normalized}));}catch(_){}return normalized;}
export function resolveAppearanceBackground(prefs){const p=normalizeAppearance(prefs);if(p.background==="custom")return p.backgroundCustom||"";const builtin=APPEARANCE_BACKGROUNDS.find(x=>x.id===p.background);if(builtin)return builtin.src||"";return p.savedBackgrounds.find(x=>x.id===p.background)?.src||p.backgroundCustom||"";}
function hexToRgba(hex,alpha){const raw=String(hex||"").replace("#","");const full=raw.length===3?raw.split("").map(x=>x+x).join(""):raw;const n=parseInt(full,16);return`rgba(${(n>>16)&255},${(n>>8)&255},${n&255},${alpha})`;}function cssUrl(value){return String(value||"").replace(/\\/g,"\\\\").replace(/"/g,"\\\"").replace(/[\r\n]/g,"");}
function ensureRuntimeStyle(){let el=document.getElementById("dm-user-appearance-style");if(!el){el=document.createElement("style");el.id="dm-user-appearance-style";document.head.appendChild(el);}el.textContent=`html{--dm-accent:#e8001d;--dm-accent-dim:rgba(232,0,29,.12);--dm-panel-opacity:.55;--dm-bg-dim:.48;--dm-bg-blur:0px;--dm-bg-image:url("/img/embedded/home-welcome-b80067ac.jpg");background:#0d0d0d!important;}html,body,#root{margin:0!important;padding:0!important;width:100%!important;min-width:100%!important;min-height:100%!important;background-color:transparent!important;}body{position:relative!important;background:#0d0d0d!important;}body::before{content:"";position:fixed;inset:calc(-1 * var(--dm-bg-blur));z-index:0;background-image:var(--dm-bg-image);background-size:cover;background-position:center;background-repeat:no-repeat;filter:blur(var(--dm-bg-blur));transform:scale(1.02);pointer-events:none;}body::after{content:"";position:fixed;inset:0;z-index:0;background:rgba(0,0,0,var(--dm-bg-dim));pointer-events:none;}#root{position:relative!important;z-index:1!important;min-height:100dvh!important;background:transparent!important;}.dm-app-shell,.dm-app-content{background:transparent!important;}.dm-home{background-color:transparent!important;background-image:var(--dm-bg-image)!important;background-size:cover!important;background-position:center!important;background-repeat:no-repeat!important;background-attachment:fixed!important;}.dm-home>img[alt="Delta Mining"]{display:none!important;}.dm-app-sidebar{background:rgba(22,22,22,var(--dm-panel-opacity))!important;}.dm-app-content>div:first-child{background:rgba(22,22,22,calc(var(--dm-panel-opacity) + .10))!important;}html[data-dm-density="compact"] .dm-app-content table td,html[data-dm-density="compact"] .dm-app-content table th{padding-top:5px!important;padding-bottom:5px!important;font-size:11px!important;}html[data-dm-density="comfortable"] .dm-app-content table td,html[data-dm-density="comfortable"] .dm-app-content table th{padding-top:11px!important;padding-bottom:11px!important;}html[data-dm-scale="small"] .dm-app-shell{zoom:.92;}html[data-dm-scale="large"] .dm-app-shell{zoom:1.08;}html[data-dm-reduced-motion="1"] *,html[data-dm-reduced-motion="1"] *::before,html[data-dm-reduced-motion="1"] *::after{animation-duration:.001ms!important;animation-iteration-count:1!important;transition-duration:.001ms!important;scroll-behavior:auto!important;}`;return el;}
export function applyAppearance(prefs,C){if(typeof document==="undefined")return normalizeAppearance(prefs);const p=normalizeAppearance(prefs),accent=APPEARANCE_ACCENTS.find(x=>x.id===p.accent)?.hex||"#e8001d";if(C){C.accent=accent;C.accentDim=hexToRgba(accent,.12);}const background=resolveAppearanceBackground(p);ensureRuntimeStyle();const root=document.documentElement;root.style.setProperty("--dm-accent",accent);root.style.setProperty("--dm-accent-dim",hexToRgba(accent,.12));root.style.setProperty("--dm-panel-opacity",String(p.panelOpacity/100));root.style.setProperty("--dm-bg-dim",String(p.backgroundDim/100));root.style.setProperty("--dm-bg-blur",`${p.backgroundBlur}px`);root.style.setProperty("--dm-bg-image",background?`url("${cssUrl(background)}")`:"none");root.dataset.dmDensity=p.density;root.dataset.dmScale=p.scale;root.dataset.dmReducedMotion=p.reducedMotion?"1":"0";return p;}
export function resolveSidebarPreference(prefs,remembered=true){const p=normalizeAppearance(prefs);if(p.sidebar==="expanded")return true;if(p.sidebar==="compact")return false;return remembered;}
export async function loadCentralAppearance(_url,email){
  const {data,error}=await requireSupabase().rpc("app_get_user_appearance",{p_email:String(email||"")});
  if(error)throw error;
  return normalizeAppearance({...data?.appearance,savedBackgrounds:data?.backgrounds||[]});
}
export async function uploadUserBackground(_url,email,dataUrl,name){
  const {data,error}=await requireSupabase().rpc("app_upload_user_background",{p_email:String(email||""),p_name:String(name||"Mi fondo"),p_data_url:String(dataUrl||"")});
  if(error)throw error;
  return data;
}
export async function saveCentralAppearance(_url,email,prefs){
  const normalized=normalizeAppearance(prefs);
  const {data,error}=await requireSupabase().rpc("app_save_user_appearance",{p_email:String(email||""),p_appearance:normalized});
  if(error)throw error;
  return normalizeAppearance({...normalized,...data?.appearance,savedBackgrounds:data?.backgrounds||data?.appearance?.savedBackgrounds||normalized.savedBackgrounds});
}
export async function fileToBackgroundDataUrl(file){if(!file)return"";if(!String(file.type||"").startsWith("image/"))throw new Error("Seleccioná una imagen válida.");if(file.size>8*1024*1024)throw new Error("La imagen no puede superar 8 MB.");const bitmap=await window.createImageBitmap(file),maxW=1600,maxH=900,scale=Math.min(1,maxW/bitmap.width,maxH/bitmap.height),canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));canvas.getContext("2d").drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close?.();return canvas.toDataURL("image/jpeg",.68);}
