import {requireSupabase} from "./supabaseClient.js";
export const DEFAULT_APPEARANCE=Object.freeze({accent:"red",background:"operations",backgroundCustom:"",backgroundCustomName:"",savedBackgrounds:[],backgroundDim:48,backgroundBlur:0,panelOpacity:55,density:"normal",scale:"normal",sidebar:"remember",reducedMotion:false});
export const APPEARANCE_ACCENTS=Object.freeze([{id:"red",label:"Rojo Delta",hex:"#e8001d"},{id:"blue",label:"Azul",hex:"#3b82f6"},{id:"cyan",label:"Celeste",hex:"#06b6d4"},{id:"green",label:"Verde",hex:"#22c55e"},{id:"orange",label:"Naranja",hex:"#f59e0b"},{id:"purple",label:"Violeta",hex:"#a855f7"}]);
export const APPEARANCE_BACKGROUNDS=Object.freeze([{id:"operations",label:"Cordillera",src:"/img/embedded/home-welcome-b80067ac.jpg",previewFit:"cover"},{id:"login",label:"Delta",src:"/img/embedded/home-inline-0c79147d.png",previewFit:"contain"},{id:"none",label:"Sin imagen",src:"",previewFit:"cover"}]);
const LAST="dm_last_appearance_v1",key=e=>`dm_appearance_v1:${String(e||"anonymous").trim().toLowerCase()}`;
const safe=v=>(Array.isArray(v)?v:[]).map((x,i)=>({id:String(x?.id||`user:${i}`),label:String(x?.label||`Mi fondo ${i+1}`),src:String(x?.src||""),thumbnail:String(x?.thumbnail||x?.src||"")})).filter(x=>x.id&&x.src);
export function normalizeAppearance(v={}){const p={...DEFAULT_APPEARANCE,...(v||{})};p.savedBackgrounds=safe(p.savedBackgrounds||p.backgrounds);if(!APPEARANCE_ACCENTS.some(x=>x.id===p.accent))p.accent="red";if(!APPEARANCE_BACKGROUNDS.some(x=>x.id===p.background)&&!p.savedBackgrounds.some(x=>x.id===p.background)&&p.background!=="custom")p.background="operations";p.backgroundDim=Math.max(0,Math.min(85,Number(p.backgroundDim??48)));p.backgroundBlur=Math.max(0,Math.min(16,Number(p.backgroundBlur??0)));p.panelOpacity=Math.max(35,Math.min(100,Number(p.panelOpacity??55)));if(!["compact","normal","comfortable"].includes(p.density))p.density="normal";if(!["small","normal","large"].includes(p.scale))p.scale="normal";if(!["remember","expanded","compact"].includes(p.sidebar))p.sidebar="remember";p.reducedMotion=!!p.reducedMotion;return p;}
export function readLocalAppearance(e){try{return normalizeAppearance(JSON.parse(localStorage.getItem(key(e))||"{}"));}catch{return normalizeAppearance();}}
export function readLastAppearance(){try{return normalizeAppearance(JSON.parse(localStorage.getItem(LAST)||"{}"));}catch{return normalizeAppearance();}}
export function writeLocalAppearance(e,p){const n=normalizeAppearance(p);try{localStorage.setItem(key(e),JSON.stringify(n));localStorage.setItem(LAST,JSON.stringify(n));window.dispatchEvent(new CustomEvent("dm-appearance-saved",{detail:n}));}catch{}return n;}
export function resolveAppearanceBackground(v){const p=normalizeAppearance(v);if(p.background==="custom")return p.backgroundCustom||"";const b=APPEARANCE_BACKGROUNDS.find(x=>x.id===p.background);return b?.src||p.savedBackgrounds.find(x=>x.id===p.background)?.src||"";}
const rgba=(h,a)=>{const n=parseInt(String(h).replace("#",""),16);return`rgba(${(n>>16)&255},${(n>>8)&255},${n&255},${a})`;};
export function applyAppearance(v,C){if(typeof document==="undefined")return normalizeAppearance(v);const p=normalizeAppearance(v),accent=APPEARANCE_ACCENTS.find(x=>x.id===p.accent)?.hex||"#e8001d",bg=resolveAppearanceBackground(p),r=document.documentElement;if(C){C.accent=accent;C.accentDim=rgba(accent,.12);}r.style.setProperty("--dm-accent",accent);r.style.setProperty("--dm-accent-dim",rgba(accent,.12));r.style.setProperty("--dm-panel-opacity",String(p.panelOpacity/100));r.style.setProperty("--dm-bg-dim",String(p.backgroundDim/100));r.style.setProperty("--dm-bg-blur",`${p.backgroundBlur}px`);r.style.setProperty("--dm-bg-image",bg?`url("${String(bg).replace(/"/g,"%22")}")`:"none");r.dataset.dmDensity=p.density;r.dataset.dmScale=p.scale;r.dataset.dmReducedMotion=p.reducedMotion?"1":"0";document.body.style.backgroundImage=bg?`linear-gradient(rgba(0,0,0,${p.backgroundDim/100}),rgba(0,0,0,${p.backgroundDim/100})),url("${String(bg).replace(/"/g,"%22")}")`:"none";document.body.style.backgroundSize="cover";document.body.style.backgroundPosition="center";document.body.style.backgroundAttachment="fixed";return p;}
export function resolveSidebarPreference(v,remembered=true){const p=normalizeAppearance(v);return p.sidebar==="expanded"?true:p.sidebar==="compact"?false:remembered;}
export async function loadCentralAppearance(_url,e){const {data,error}=await requireSupabase().rpc("app_get_user_appearance",{p_email:String(e||"")});if(error)throw error;return normalizeAppearance({...data?.appearance,savedBackgrounds:data?.backgrounds||[]});}
export async function saveCentralAppearance(_url,e,p){const {data,error}=await requireSupabase().rpc("app_save_user_appearance",{p_email:String(e||""),p_appearance:normalizeAppearance(p)});if(error)throw error;return normalizeAppearance({...data?.appearance,savedBackgrounds:data?.backgrounds||[]});}
export async function uploadUserBackground(_url,e,dataUrl,name){const {data,error}=await requireSupabase().rpc("app_upload_user_background",{p_email:String(e||""),p_name:String(name||"Mi fondo"),p_data_url:String(dataUrl||"")});if(error)throw error;return data;}
export async function fileToBackgroundDataUrl(file){if(!file)return"";if(!String(file.type||"").startsWith("image/"))throw new Error("Seleccioná una imagen válida.");if(file.size>8*1024*1024)throw new Error("La imagen no puede superar 8 MB.");const bitmap=await createImageBitmap(file),scale=Math.min(1,1600/bitmap.width,900/bitmap.height),canvas=document.createElement("canvas");canvas.width=Math.max(1,Math.round(bitmap.width*scale));canvas.height=Math.max(1,Math.round(bitmap.height*scale));canvas.getContext("2d").drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close?.();return canvas.toDataURL("image/jpeg",.68);}
