import React,{useEffect,useMemo,useRef,useState} from "react";
import {C} from "../../components/ui/index.jsx";
import {deleteTallerMovement,getCachedTallerMovements,getTallerMovements,saveTallerMovement,updateTallerMovement} from "../../services/tallerMovements.js";

const norm=v=>String(v??"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toUpperCase().replace(/[^A-Z0-9]/g,"");
const pick=(row,names)=>{const keys=Object.keys(row||{});for(const n of names){const k=keys.find(x=>norm(x)===norm(n));if(k)return row[k];}for(const n of names){const k=keys.find(x=>norm(x).includes(norm(n))||norm(n).includes(norm(x)));if(k)return row[k];}return"";};
const code=v=>{const raw=String(v||"").trim().toUpperCase().replace(/\s*\(.*?\)/g,"").replace(/[^A-Z0-9]/g,"");const m=raw.match(/^([A-Z]{2,4})(\d{1,6})$/);return m?`${m[1]}-${m[2].padStart(4,"0")}`:String(v||"").trim().toUpperCase();};
const project=v=>String(v||"").trim().toUpperCase();
const inputStyle={height:40,borderRadius:8,border:`1px solid ${C.border}`,background:"#151515",color:C.text,padding:"0 11px",outline:"none",fontSize:12,boxSizing:"border-box",width:"100%"};
const labelStyle={display:"flex",flexDirection:"column",gap:6,fontSize:11,fontWeight:800,color:C.textSub};
const btn=(color,dim)=>({border:`1px solid ${color}`,background:dim,color,borderRadius:8,padding:"8px 12px",fontWeight:800,cursor:"pointer",fontSize:11});
function Field({label,children}){return <label style={labelStyle}>{label}{children}</label>}
function Input({value,onChange,...rest}){return <input value={value??""} onChange={e=>onChange?.(e.target.value)} style={inputStyle} {...rest}/>}
function Select({value,onChange,children,disabled=false}){return <select value={value??""} onChange={e=>onChange?.(e.target.value)} disabled={disabled} style={{...inputStyle,opacity:disabled?.6:1}}>{children}</select>}

function buildCatalog(listaEquipos=[],rop02All=[]){
  const latest=new Map();
  for(const r of rop02All||[]){
    const interno=code(r?.maquina||r?._internoRaw),fecha=String(r?.fecha||"").slice(0,10);
    if(!interno||!fecha)continue;
    const cur=latest.get(interno);
    if(!cur||fecha>cur.fecha)latest.set(interno,{fecha,proyecto:project(r?.proyecto||r?.lugar),horometro:Number(r?.horometroFinal??r?.hf??r?.horometro??0)||0});
  }
  const out=new Map();
  for(const r of listaEquipos||[]){
    const interno=code(pick(r,["Codigo nuevo","Código nuevo","Código interno","Interno","Codigo Drusila","Código Drusila"]));
    if(!interno)continue;
    const last=latest.get(interno)||{};
    out.set(interno,{interno,equipo:String(pick(r,["Familia","Tipo de equipo","Equipo","Descripción","Descripcion"])||"").trim(),marca:String(pick(r,["Marca"])||"").trim(),modelo:String(pick(r,["Modelo"])||"").trim(),propiedad:String(pick(r,["Propiedad"])||"").trim(),proyecto:last.proyecto||project(pick(r,["Lugar de alquiler","Proyecto","Lugar"])),horometro:last.horometro||Number(pick(r,["Horas","Horometro","Horómetro"]))||0,ultimaCarga:last.fecha||""});
  }
  for(const [interno,last] of latest)if(!out.has(interno))out.set(interno,{interno,equipo:"",marca:"",modelo:"",propiedad:"",proyecto:last.proyecto,horometro:last.horometro,ultimaCarga:last.fecha});
  return[...out.values()].sort((a,b)=>a.interno.localeCompare(b.interno,"es",{numeric:true}));
}

const EMPTY={equipo:"",marca:"",modelo:"",propiedad:"DELTA",interno:"",horometro:"",proyectoOrigen:"",proyectoDestino:"",motivoBaja:"MANTENIMIENTO",motivoOtro:"",internoModo:"MISMO",internoNuevo:"",observacion:"",equipoSale:"",equipoEntra:"",marcaEntra:"",modeloEntra:"",propiedadEntra:"DELTA",internoEntra:"",horometroEntra:""};
const apiRow=r=>({id:r.ID||r.id,fechaHora:r.FECHA_HORA||r.fechaHora,tipo:r.TIPO||r.tipo,equipo:r.EQUIPO||r.equipo,marca:r.MARCA||r.marca,modelo:r.MODELO||r.modelo,propiedad:r.PROPIEDAD||r.propiedad,interno:r.INTERNO_ORIGEN||r.interno,horometro:r.HOROMETRO||r.horometro,proyectoOrigen:r.PROYECTO_ORIGEN||r.proyectoOrigen,proyectoDestino:r.PROYECTO_DESTINO||r.proyectoDestino,internoDestino:r.INTERNO_DESTINO||r.internoDestino,internoEntra:r.INTERNO_ENTRA||r.internoEntra,equipoEntra:r.EQUIPO_ENTRA||r.equipoEntra,marcaEntra:r.MARCA_ENTRA||r.marcaEntra,modeloEntra:r.MODELO_ENTRA||r.modeloEntra,propiedadEntra:r.PROPIEDAD_ENTRA||r.propiedadEntra,horometroEntra:r.HOROMETRO_ENTRA||r.horometroEntra,motivo:r.MOTIVO||r.motivo,observacion:r.OBSERVACION||r.observacion,usuario:r.USUARIO||r.usuario});

export default function TallerCentralMovementPageSupabase({mode="SUBIDA",listaEquipos=[],rop02All=[]}){
  const tipo=String(mode||"SUBIDA").toUpperCase();
  const requestRef=useRef(0);
  const [form,setForm]=useState(EMPTY),[rows,setRows]=useState(()=>getCachedTallerMovements(tipo).map(apiRow)),[saving,setSaving]=useState(false),[msg,setMsg]=useState(""),[editingId,setEditingId]=useState("");
  const catalog=useMemo(()=>buildCatalog(listaEquipos,rop02All),[listaEquipos,rop02All]);
  const projects=useMemo(()=>[...new Set((rop02All||[]).map(r=>project(r?.proyecto||r?.lugar)).filter(Boolean))].sort(),[rop02All]);
  const propertyOptions=useMemo(()=>{const vals=[...new Set((listaEquipos||[]).map(r=>String(pick(r,["Propiedad"])||"").trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b,"es"));if(!vals.some(v=>norm(v)===norm("OTRO")))vals.push("OTRO");return vals.length?vals:["DELTA","ALQUILADO","OTRO"];},[listaEquipos]);
  const selected=useMemo(()=>catalog.find(x=>x.interno===form.interno)||null,[catalog,form.interno]);
  const outgoing=useMemo(()=>catalog.find(x=>x.interno===form.equipoSale)||null,[catalog,form.equipoSale]);

  const load=async()=>{const requestId=++requestRef.current;try{const all=await getTallerMovements(tipo,{force:true});if(requestId!==requestRef.current)return;setRows(all.map(apiRow).sort((a,b)=>String(b.fechaHora).localeCompare(String(a.fechaHora))).slice(0,100));}catch(e){if(requestId===requestRef.current)setMsg(e?.message||"No se pudo actualizar el historial.");}};
  useEffect(()=>{requestRef.current+=1;setForm(EMPTY);setEditingId("");setMsg("");const cached=getCachedTallerMovements(tipo).map(apiRow).sort((a,b)=>String(b.fechaHora).localeCompare(String(a.fechaHora))).slice(0,100);setRows(cached);load();},[tipo]);
  useEffect(()=>{if(selected)setForm(f=>({...f,equipo:selected.equipo,marca:selected.marca,modelo:selected.modelo,propiedad:selected.propiedad||f.propiedad,horometro:selected.horometro||f.horometro,proyectoOrigen:selected.proyecto||""}));},[selected]);
  useEffect(()=>{if(outgoing)setForm(f=>({...f,proyectoOrigen:outgoing.proyecto||"",horometro:outgoing.horometro||0}));},[outgoing]);
  const set=(k,v)=>setForm(f=>({...f,[k]:v}));

  const buildMovement=()=>{
    let interno=code(form.interno);
    let m={tipo,equipo:form.equipo,marca:form.marca,modelo:form.modelo,propiedad:form.propiedad,interno,horometro:Number(form.horometro)||0,proyectoOrigen:project(form.proyectoOrigen),proyectoDestino:project(form.proyectoDestino),internoDestino:interno,internoEntra:"",equipoEntra:"",marcaEntra:"",modeloEntra:"",propiedadEntra:"",horometroEntra:0,motivo:"",observacion:form.observacion,fechaUltimoRop02:selected?.ultimaCarga||new Date().toISOString().slice(0,10)};
    if(tipo==="SUBIDA"){if(!interno||!m.proyectoDestino)throw new Error("Completá interno y proyecto destino.");m.motivo=`Subida de equipo a ${m.proyectoDestino}`;}
    if(tipo==="BAJA"){if(!interno)throw new Error("Seleccioná el equipo que baja.");const detail=String(form.observacion||form.motivoOtro||(form.motivoBaja||"").replaceAll("_"," ")).trim();m.proyectoDestino="SAN JUAN";m.motivo=detail?`Se baja a SJ por ${detail}`:"Se baja a SJ";}
    if(tipo==="MOVILIZACION"){if(!interno||!m.proyectoOrigen||!m.proyectoDestino)throw new Error("Seleccioná equipo, origen y destino.");if(m.proyectoOrigen===m.proyectoDestino)throw new Error("El destino debe ser distinto del proyecto actual.");m.internoDestino=form.internoModo==="NUEVO"?code(form.internoNuevo):interno;if(!m.internoDestino)throw new Error("Ingresá el interno nuevo.");m.motivo=m.internoDestino!==interno?`Se moviliza a ${m.proyectoDestino} con interno ${m.internoDestino}`:`Se moviliza a ${m.proyectoDestino}`;}
    if(tipo==="CAMBIO_EQUIPO"){if(!outgoing)throw new Error("Seleccioná el equipo que está trabajando.");const incoming=code(form.internoEntra);if(!incoming||!form.equipoEntra)throw new Error("Completá equipo e interno del equipo que sube.");m={...m,equipo:outgoing.equipo,marca:outgoing.marca,modelo:outgoing.modelo,propiedad:outgoing.propiedad,interno:outgoing.interno,horometro:outgoing.horometro,proyectoOrigen:outgoing.proyecto,proyectoDestino:"SAN JUAN",internoDestino:outgoing.interno,internoEntra:incoming,motivo:`Se cambia equipo por ${incoming}`,equipoEntra:form.equipoEntra,marcaEntra:form.marcaEntra,modeloEntra:form.modeloEntra,propiedadEntra:form.propiedadEntra,horometroEntra:Number(form.horometroEntra)||0,fechaUltimoRop02:outgoing.ultimaCarga||new Date().toISOString().slice(0,10)};}
    return m;
  };

  const save=async()=>{setSaving(true);setMsg("");try{const movement=buildMovement();if(editingId)await updateTallerMovement(editingId,movement);else await saveTallerMovement(movement);setForm(EMPTY);setEditingId("");setMsg(editingId?"Movimiento actualizado correctamente.":"Movimiento guardado correctamente.");await load();}catch(e){setMsg(e?.message||"No se pudo guardar el movimiento.");}finally{setSaving(false);}};
  const edit=row=>{setEditingId(row.id);setMsg("");if(tipo==="CAMBIO_EQUIPO")setForm({...EMPTY,equipoSale:row.interno,equipoEntra:row.equipoEntra,marcaEntra:row.marcaEntra,modeloEntra:row.modeloEntra,propiedadEntra:row.propiedadEntra||"DELTA",internoEntra:row.internoEntra,horometroEntra:row.horometroEntra,observacion:row.observacion||""});else setForm({...EMPTY,equipo:row.equipo,marca:row.marca,modelo:row.modelo,propiedad:row.propiedad||"DELTA",interno:row.interno,horometro:row.horometro,proyectoOrigen:row.proyectoOrigen,proyectoDestino:row.proyectoDestino,internoModo:row.internoDestino&&code(row.internoDestino)!==code(row.interno)?"NUEVO":"MISMO",internoNuevo:row.internoDestino,observacion:row.observacion||""});window.scrollTo({top:0,behavior:"smooth"});};
  const remove=async row=>{if(!window.confirm(`¿Eliminar el movimiento de ${row.interno}?`))return;setSaving(true);try{await deleteTallerMovement(row.id);if(editingId===row.id){setEditingId("");setForm(EMPTY);}setMsg("Movimiento eliminado.");await load();}catch(e){setMsg(e?.message||"No se pudo eliminar.");}finally{setSaving(false);}};
  const title=tipo==="SUBIDA"?"Registrar subida":tipo==="BAJA"?"Registrar bajada":tipo==="MOVILIZACION"?"Registrar movilización":"Registrar cambio de equipo";

  return <div style={{display:"flex",flexDirection:"column",gap:14}}>
    <div style={{background:"rgba(24,24,24,.94)",border:`1px solid ${C.border}`,borderRadius:12,padding:16,display:"flex",flexDirection:"column",gap:14}}>
      <div><div style={{fontSize:16,fontWeight:900,color:C.text}}>{editingId?`Editar — ${title}`:title}</div><div style={{fontSize:11,color:C.textMuted,marginTop:3}}>Los movimientos se guardan en Supabase. Bajadas, movilizaciones y cambios de equipo se vinculan automáticamente con Atraso.</div></div>
      {tipo==="SUBIDA"&&<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:12}}><Field label="Equipo"><Input value={form.equipo} onChange={v=>set("equipo",v)}/></Field><Field label="Marca"><Input value={form.marca} onChange={v=>set("marca",v)}/></Field><Field label="Modelo"><Input value={form.modelo} onChange={v=>set("modelo",v)}/></Field><Field label="Propiedad"><Select value={form.propiedad} onChange={v=>set("propiedad",v)}>{propertyOptions.map(p=><option key={p} value={p}>{p}</option>)}</Select></Field><Field label="Interno"><Input value={form.interno} onChange={v=>set("interno",v.toUpperCase())}/></Field><Field label="Horómetro"><Input type="number" value={form.horometro} onChange={v=>set("horometro",v)}/></Field><Field label="Proyecto destino"><Select value={form.proyectoDestino} onChange={v=>set("proyectoDestino",v)}><option value="">Seleccionar...</option>{projects.map(p=><option key={p}>{p}</option>)}</Select></Field></div>}
      {["BAJA","MOVILIZACION"].includes(tipo)&&<div style={{display:"flex",flexDirection:"column",gap:12}}><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(210px,1fr))",gap:12}}><Field label="Equipo"><Select value={form.interno} onChange={v=>set("interno",v)}><option value="">Seleccionar equipo...</option>{catalog.map(x=><option key={x.interno} value={x.interno}>{x.interno}{x.equipo?` · ${x.equipo}`:""}</option>)}</Select></Field><Field label="Proyecto actual"><Input value={form.proyectoOrigen} disabled/></Field><Field label="Horómetro"><Input value={String(form.horometro||"")} disabled/></Field></div>{tipo==="BAJA"?<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(210px,1fr))",gap:12}}><Field label="Razón de bajada"><Select value={form.motivoBaja} onChange={v=>set("motivoBaja",v)}><option value="MANTENIMIENTO">Mantenimiento</option><option value="REPARACION">Reparación</option><option value="DESMOVILIZACION">Desmovilización</option><option value="FIN_ALQUILER">Fin de alquiler</option><option value="BAJA_DEFINITIVA">Baja definitiva</option><option value="OTRO">Otra</option></Select></Field>{form.motivoBaja==="OTRO"&&<Field label="Detalle"><Input value={form.motivoOtro} onChange={v=>set("motivoOtro",v)}/></Field>}</div>:<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(210px,1fr))",gap:12}}><Field label="Proyecto destino"><Select value={form.proyectoDestino} onChange={v=>set("proyectoDestino",v)}><option value="">Seleccionar...</option>{projects.filter(p=>p!==form.proyectoOrigen).map(p=><option key={p}>{p}</option>)}</Select></Field><Field label="Interno destino"><Select value={form.internoModo} onChange={v=>set("internoModo",v)}><option value="MISMO">Mantiene interno</option><option value="NUEVO">Nuevo interno</option></Select></Field>{form.internoModo==="NUEVO"&&<Field label="Nuevo interno"><Input value={form.internoNuevo} onChange={v=>set("internoNuevo",v.toUpperCase())}/></Field>}</div>}</div>}
      {tipo==="CAMBIO_EQUIPO"&&<div style={{display:"flex",flexDirection:"column",gap:14}}><div style={{fontSize:12,fontWeight:900,color:C.red}}>Equipo que sale de operación</div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(210px,1fr))",gap:12}}><Field label="Equipo trabajando"><Select value={form.equipoSale} onChange={v=>set("equipoSale",v)}><option value="">Seleccionar...</option>{catalog.map(x=><option key={x.interno} value={x.interno}>{x.interno}{x.equipo?` · ${x.equipo}`:""}</option>)}</Select></Field><Field label="Proyecto"><Input value={outgoing?.proyecto||""} disabled/></Field><Field label="Horómetro"><Input value={String(outgoing?.horometro||"")} disabled/></Field></div><div style={{fontSize:12,fontWeight:900,color:C.green}}>Equipo que sube como reemplazo</div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:12}}><Field label="Equipo"><Input value={form.equipoEntra} onChange={v=>set("equipoEntra",v)}/></Field><Field label="Marca"><Input value={form.marcaEntra} onChange={v=>set("marcaEntra",v)}/></Field><Field label="Modelo"><Input value={form.modeloEntra} onChange={v=>set("modeloEntra",v)}/></Field><Field label="Propiedad"><Select value={form.propiedadEntra} onChange={v=>set("propiedadEntra",v)}>{propertyOptions.map(p=><option key={p} value={p}>{p}</option>)}</Select></Field><Field label="Interno"><Input value={form.internoEntra} onChange={v=>set("internoEntra",v.toUpperCase())}/></Field><Field label="Horómetro"><Input type="number" value={form.horometroEntra} onChange={v=>set("horometroEntra",v)}/></Field></div></div>}
      <Field label="Observación"><Input value={form.observacion} onChange={v=>set("observacion",v)} placeholder="Opcional"/></Field>
      {msg&&<div style={{fontSize:12,fontWeight:800,color:msg.includes("correctamente")||msg.includes("eliminado")?C.green:C.red}}>{msg}</div>}
      <div style={{display:"flex",justifyContent:"flex-end",gap:8}}>{editingId&&<button onClick={()=>{setEditingId("");setForm(EMPTY);setMsg("");}} style={btn(C.textSub,C.surface)}>Cancelar edición</button>}<button onClick={save} disabled={saving} style={{...btn(C.green,C.greenDim),opacity:saving?.6:1}}>{saving?"Guardando...":editingId?"Guardar cambios":"Guardar movimiento"}</button></div>
    </div>
    <div style={{background:"rgba(24,24,24,.94)",border:`1px solid ${C.border}`,borderRadius:12,overflow:"hidden"}}><div style={{padding:"12px 14px",fontWeight:900,color:C.text}}>Últimos 100 movimientos</div><div style={{overflowX:"auto",maxHeight:420}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:11}}><thead><tr>{["Fecha","Interno","Equipo","Origen","Destino","Interno destino","Motivo","Usuario","Acciones"].map(h=><th key={h} style={{textAlign:"left",padding:"9px 10px",borderTop:`1px solid ${C.border}`,borderBottom:`1px solid ${C.border}`,color:C.textMuted,background:"#151515"}}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id||i}><td style={{padding:9}}>{String(r.fechaHora||"").slice(0,10)}</td><td style={{padding:9,color:C.purple,fontWeight:800}}>{r.interno}</td><td style={{padding:9}}>{r.equipo||"—"}</td><td style={{padding:9}}>{r.proyectoOrigen||"—"}</td><td style={{padding:9}}>{r.proyectoDestino||"—"}</td><td style={{padding:9}}>{r.tipo==="CAMBIO_EQUIPO"?(r.internoEntra||"—"):(r.internoDestino||"—")}</td><td style={{padding:9}}>{r.motivo||"—"}</td><td style={{padding:9}}>{r.usuario||"—"}</td><td style={{padding:9,display:"flex",gap:6}}><button onClick={()=>edit(r)} style={btn(C.blue,C.blueDim)}>Editar</button><button onClick={()=>remove(r)} style={btn(C.red,C.redDim)}>Eliminar</button></td></tr>)}{!rows.length&&<tr><td colSpan={9} style={{padding:20,textAlign:"center",color:C.textMuted}}>Sin movimientos registrados</td></tr>}</tbody></table></div></div>
  </div>;
}
