import React,{useEffect,useMemo,useState} from "react";
import {C} from "../../components/ui/index.jsx";
import {cancelEquipmentMovement,saveEquipmentMovement,useEquipmentMovements} from "../../services/equipmentMovements.js";

const TAG="DM_TALLER";
const norm=v=>String(v??"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toUpperCase().replace(/[^A-Z0-9]/g,"");
const pick=(row,names)=>{const keys=Object.keys(row||{});for(const n of names){const nn=norm(n),k=keys.find(x=>norm(x)===nn);if(k)return row[k];}for(const n of names){const nn=norm(n),k=keys.find(x=>norm(x).includes(nn)||nn.includes(norm(x)));if(k)return row[k];}return"";};
const code=v=>{const raw=String(v||"").trim().toUpperCase().replace(/\s*\(.*?\)/g,"").replace(/[^A-Z0-9]/g,"");const m=raw.match(/^([A-Z]{2,4})(\d{1,6})$/);return m?`${m[1]}-${m[2].padStart(4,"0")}`:String(v||"").trim().toUpperCase();};
const project=v=>String(v||"").trim().toUpperCase();
const esc=v=>String(v??"").replace(/\]/g,")");
const metadata=m=>`[${TAG}:1][TIPO:${esc(m.tipo)}][EQUIPO:${esc(m.equipo)}][MARCA:${esc(m.marca)}][MODELO:${esc(m.modelo)}][PROPIEDAD:${esc(m.propiedad)}][INTERNO:${esc(m.interno)}][HOROMETRO:${esc(m.horometro)}][ORIGEN:${esc(m.proyectoOrigen)}][DESTINO:${esc(m.proyectoDestino)}][INTERNO_DESTINO:${esc(m.internoDestino)}][MOTIVO:${esc(m.motivo)}][EQUIPO_ENTRA:${esc(m.equipoEntra)}][MARCA_ENTRA:${esc(m.marcaEntra)}][MODELO_ENTRA:${esc(m.modeloEntra)}][PROPIEDAD_ENTRA:${esc(m.propiedadEntra)}][HOROMETRO_ENTRA:${esc(m.horometroEntra)}][USUARIO:${esc(m.usuario)}] ${esc(m.observacion)}`;
const field=(raw,key)=>{const m=String(raw||"").match(new RegExp(`\\[${key}:([^\\]]*)\\]`,`i`));return m?m[1]:"";};
const parseMovement=m=>{const obs=String(m?.observacion||"");if(!obs.includes(`[${TAG}:1]`))return null;return{id:m.id||"",fechaHora:m.fechaHora||"",tipo:field(obs,"TIPO"),equipo:field(obs,"EQUIPO"),marca:field(obs,"MARCA"),modelo:field(obs,"MODELO"),propiedad:field(obs,"PROPIEDAD"),interno:field(obs,"INTERNO")||m.interno,horometro:field(obs,"HOROMETRO"),proyectoOrigen:field(obs,"ORIGEN")||m.proyectoOrigen,proyectoDestino:field(obs,"DESTINO")||m.proyectoDestino,internoDestino:field(obs,"INTERNO_DESTINO"),motivo:field(obs,"MOTIVO"),equipoEntra:field(obs,"EQUIPO_ENTRA"),marcaEntra:field(obs,"MARCA_ENTRA"),modeloEntra:field(obs,"MODELO_ENTRA"),propiedadEntra:field(obs,"PROPIEDAD_ENTRA"),horometroEntra:field(obs,"HOROMETRO_ENTRA"),usuario:field(obs,"USUARIO")||m.usuario};};
const inputStyle={height:40,borderRadius:8,border:`1px solid ${C.border}`,background:"#151515",color:C.text,padding:"0 11px",outline:"none",fontSize:12,boxSizing:"border-box",width:"100%"};
const labelStyle={display:"flex",flexDirection:"column",gap:6,fontSize:11,fontWeight:800,color:C.textSub};
const actionStyle={border:`1px solid ${C.green}`,background:C.greenDim,color:C.green,borderRadius:8,padding:"10px 16px",fontWeight:900,cursor:"pointer"};
function Field({label,children}){return <label style={labelStyle}>{label}{children}</label>}
function Input({value,onChange,...rest}){return <input value={value} onChange={e=>onChange(e.target.value)} style={inputStyle} {...rest}/>}
function Select({value,onChange,children,disabled=false}){return <select value={value} onChange={e=>onChange(e.target.value)} disabled={disabled} style={{...inputStyle,opacity:disabled?.6:1}}>{children}</select>}
function buildCatalog(listaEquipos=[],rop02All=[]){const latest=new Map();for(const r of rop02All||[]){const interno=code(r?.maquina||r?._internoRaw),fecha=String(r?.fecha||"").slice(0,10);if(!interno||!fecha)continue;const cur=latest.get(interno);if(!cur||fecha>cur.fecha)latest.set(interno,{fecha,proyecto:project(r?.proyecto||r?.lugar),horometro:Number(r?.horometroFinal??r?.hf??r?.horometro??0)||0});}const out=new Map();for(const r of listaEquipos||[]){const interno=code(pick(r,["Codigo nuevo","Código nuevo","Código interno","Interno","Codigo Drusila","Código Drusila"]));if(!interno)continue;const last=latest.get(interno)||{};out.set(interno,{interno,equipo:String(pick(r,["Familia","Tipo de equipo","Equipo","Descripción","Descripcion"])||"").trim(),marca:String(pick(r,["Marca"])||"").trim(),modelo:String(pick(r,["Modelo"])||"").trim(),propiedad:String(pick(r,["Propiedad"])||"").trim(),proyecto:last.proyecto||project(pick(r,["Lugar de alquiler","Proyecto","Lugar"])),horometro:last.horometro||Number(pick(r,["Horas","Horometro","Horómetro"]))||0,ultimaCarga:last.fecha||""});}for(const [interno,last] of latest)if(!out.has(interno))out.set(interno,{interno,equipo:"",marca:"",modelo:"",propiedad:"",proyecto:last.proyecto,horometro:last.horometro,ultimaCarga:last.fecha});return[...out.values()].sort((a,b)=>a.interno.localeCompare(b.interno,"es",{numeric:true}));}
const EMPTY={equipo:"",marca:"",modelo:"",propiedad:"DELTA",interno:"",horometro:"",proyectoOrigen:"",proyectoDestino:"",motivoBaja:"MANTENIMIENTO",motivoOtro:"",internoModo:"MISMO",internoNuevo:"",observacion:"",equipoSale:"",equipoEntra:"",marcaEntra:"",modeloEntra:"",propiedadEntra:"DELTA",internoEntra:"",horometroEntra:""};
export default function TallerCentralMovementPage({mode="SUBIDA",listaEquipos=[],rop02All=[]}){
 const tipo=String(mode||"SUBIDA").toUpperCase();const[form,setForm]=useState(EMPTY),[saving,setSaving]=useState(false),[msg,setMsg]=useState("");
 const{movements,reload,error}=useEquipmentMovements(rop02All,["tallerCentral"]);const catalog=useMemo(()=>buildCatalog(listaEquipos,rop02All),[listaEquipos,rop02All]);const projects=useMemo(()=>[...new Set((rop02All||[]).map(r=>project(r?.proyecto||r?.lugar)).filter(Boolean))].sort(),[rop02All]);
 const selected=useMemo(()=>catalog.find(x=>x.interno===form.interno)||null,[catalog,form.interno]);const outgoing=useMemo(()=>catalog.find(x=>x.interno===form.equipoSale)||null,[catalog,form.equipoSale]);
 useEffect(()=>{setForm(EMPTY);setMsg("");},[tipo]);useEffect(()=>{if(selected)setForm(f=>({...f,equipo:selected.equipo,marca:selected.marca,modelo:selected.modelo,propiedad:selected.propiedad||f.propiedad,horometro:selected.horometro||f.horometro,proyectoOrigen:selected.proyecto||""}));},[selected]);
 useEffect(()=>{if(outgoing)setForm(f=>({...f,proyectoOrigen:outgoing.proyecto||"",horometro:outgoing.horometro||0}));},[outgoing]);
 const set=(k,v)=>setForm(f=>({...f,[k]:v}));const rows=useMemo(()=>movements.map(parseMovement).filter(Boolean).filter(r=>r.tipo===tipo).sort((a,b)=>String(b.fechaHora).localeCompare(String(a.fechaHora))).slice(0,100),[movements,tipo]);
 const save=async()=>{let interno=code(form.interno),destino=interno,meta={tipo,fechaHora:new Date().toISOString(),equipo:form.equipo,marca:form.marca,modelo:form.modelo,propiedad:form.propiedad,interno,horometro:Number(form.horometro)||0,proyectoOrigen:project(form.proyectoOrigen),proyectoDestino:project(form.proyectoDestino),motivo:"",internoDestino:destino,equipoEntra:"",marcaEntra:"",modeloEntra:"",propiedadEntra:"",horometroEntra:"",usuario:sessionStorage.getItem("dm_user")||"Usuario",observacion:form.observacion};
  if(tipo==="SUBIDA"){if(!interno||!form.proyectoDestino)return setMsg("Completá interno y proyecto destino.");meta.motivo="SUBIDA";}
  if(tipo==="BAJA"){if(!interno)return setMsg("Seleccioná el equipo que baja.");meta.motivo=form.motivoBaja==="OTRO"?form.motivoOtro:form.motivoBaja;}
  if(tipo==="MOVILIZACION"){if(!interno||!form.proyectoOrigen||!form.proyectoDestino)return setMsg("Seleccioná equipo, origen y destino.");if(project(form.proyectoOrigen)===project(form.proyectoDestino))return setMsg("El destino debe ser distinto del proyecto actual.");destino=form.internoModo==="NUEVO"?code(form.internoNuevo):interno;if(!destino)return setMsg("Ingresá el interno nuevo.");meta.internoDestino=destino;meta.motivo="MOVILIZACION";}
  if(tipo==="CAMBIO_EQUIPO"){if(!outgoing)return setMsg("Seleccioná el equipo que está trabajando.");const incoming=code(form.internoEntra);if(!incoming||!form.equipoEntra)return setMsg("Completá equipo e interno del equipo que sube.");interno=outgoing.interno;meta={...meta,equipo:outgoing.equipo,marca:outgoing.marca,modelo:outgoing.modelo,propiedad:outgoing.propiedad,interno,horometro:outgoing.horometro,proyectoOrigen:outgoing.proyecto,proyectoDestino:outgoing.proyecto,internoDestino:incoming,motivo:"CAMBIO_EQUIPO",equipoEntra:form.equipoEntra,marcaEntra:form.marcaEntra,modeloEntra:form.modeloEntra,propiedadEntra:form.propiedadEntra,horometroEntra:Number(form.horometroEntra)||0};}
  setSaving(true);setMsg("");try{const res=await saveEquipmentMovement({interno,internoNormalizado:interno,proyectoOrigen:meta.proyectoOrigen||"TALLER CENTRAL",proyectoDestino:meta.proyectoDestino,tipoMovimiento:"OTRO",motivo:`TALLER_${tipo}`,observacion:metadata(meta),usuario:meta.usuario,fechaUltimoRop02:selected?.ultimaCarga||outgoing?.ultimaCarga||new Date().toISOString().slice(0,10)});const id=res?.movement?.id;if(id)await cancelEquipmentMovement(id,meta.usuario);await reload();setForm(EMPTY);setMsg("Movimiento guardado correctamente.");}catch(e){setMsg(e?.message||"No se pudo guardar el movimiento.");}finally{setSaving(false);}};
 const title=tipo==="SUBIDA"?"Registrar subida":tipo==="BAJA"?"Registrar bajada":tipo==="MOVILIZACION"?"Registrar movilización":"Registrar cambio de equipo";
 return <div style={{display:"flex",flexDirection:"column",gap:14}}><div style={{background:"rgba(24,24,24,.94)",border:`1px solid ${C.border}`,borderRadius:12,padding:16,display:"flex",flexDirection:"column",gap:14}}><div><div style={{fontSize:16,fontWeight:900,color:C.text}}>{title}</div><div style={{fontSize:11,color:C.textMuted,marginTop:3}}>Registro compartido de Taller Central. No modifica Atraso ni disponibilidad.</div></div>
 {tipo==="SUBIDA"&&<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:12}}><Field label="Equipo"><Input value={form.equipo} onChange={v=>set("equipo",v)}/></Field><Field label="Marca"><Input value={form.marca} onChange={v=>set("marca",v)}/></Field><Field label="Modelo"><Input value={form.modelo} onChange={v=>set("modelo",v)}/></Field><Field label="Propiedad"><Select value={form.propiedad} onChange={v=>set("propiedad",v)}><option>DELTA</option><option>ALQUILADO</option><option>OTRO</option></Select></Field><Field label="Interno"><Input value={form.interno} onChange={v=>set("interno",v.toUpperCase())}/></Field><Field label="Horómetro"><Input type="number" value={form.horometro} onChange={v=>set("horometro",v)}/></Field><Field label="Proyecto destino"><Select value={form.proyectoDestino} onChange={v=>set("proyectoDestino",v)}><option value="">Seleccionar...</option>{projects.map(p=><option key={p}>{p}</option>)}</Select></Field></div>}
 {["BAJA","MOVILIZACION"].includes(tipo)&&<div style={{display:"flex",flexDirection:"column",gap:12}}><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(210px,1fr))",gap:12}}><Field label="Equipo"><Select value={form.interno} onChange={v=>set("interno",v)}><option value="">Seleccionar equipo...</option>{catalog.map(x=><option key={x.interno} value={x.interno}>{x.interno}{x.equipo?` · ${x.equipo}`:""}</option>)}</Select></Field><Field label="Proyecto actual"><Input value={form.proyectoOrigen} onChange={()=>{}} disabled/></Field><Field label="Horómetro"><Input value={String(form.horometro||"")} onChange={()=>{}} disabled/></Field></div>{tipo==="BAJA"?<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(210px,1fr))",gap:12}}><Field label="Razón de bajada"><Select value={form.motivoBaja} onChange={v=>set("motivoBaja",v)}><option value="MANTENIMIENTO">Mantenimiento</option><option value="REPARACION">Reparación</option><option value="DESMOVILIZACION">Desmovilización</option><option value="FIN_ALQUILER">Fin de alquiler</option><option value="BAJA_DEFINITIVA">Baja definitiva</option><option value="OTRO">Otra</option></Select></Field>{form.motivoBaja==="OTRO"&&<Field label="Detalle"><Input value={form.motivoOtro} onChange={v=>set("motivoOtro",v)}/></Field>}</div>:<div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(210px,1fr))",gap:12}}><Field label="Proyecto destino"><Select value={form.proyectoDestino} onChange={v=>set("proyectoDestino",v)}><option value="">Seleccionar...</option>{projects.filter(p=>p!==form.proyectoOrigen).map(p=><option key={p}>{p}</option>)}</Select></Field><Field label="Interno destino"><Select value={form.internoModo} onChange={v=>set("internoModo",v)}><option value="MISMO">Mantiene interno</option><option value="NUEVO">Nuevo interno</option></Select></Field>{form.internoModo==="NUEVO"&&<Field label="Nuevo interno"><Input value={form.internoNuevo} onChange={v=>set("internoNuevo",v.toUpperCase())}/></Field>}</div>}</div>}
 {tipo==="CAMBIO_EQUIPO"&&<div style={{display:"flex",flexDirection:"column",gap:14}}><div style={{fontSize:12,fontWeight:900,color:C.red}}>Equipo que sale de operación</div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(210px,1fr))",gap:12}}><Field label="Equipo trabajando"><Select value={form.equipoSale} onChange={v=>set("equipoSale",v)}><option value="">Seleccionar...</option>{catalog.map(x=><option key={x.interno} value={x.interno}>{x.interno}{x.equipo?` · ${x.equipo}`:""}</option>)}</Select></Field><Field label="Proyecto"><Input value={outgoing?.proyecto||""} onChange={()=>{}} disabled/></Field><Field label="Horómetro"><Input value={String(outgoing?.horometro||"")} onChange={()=>{}} disabled/></Field></div><div style={{fontSize:12,fontWeight:900,color:C.green}}>Equipo que sube como reemplazo</div><div style={{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:12}}><Field label="Equipo"><Input value={form.equipoEntra} onChange={v=>set("equipoEntra",v)}/></Field><Field label="Marca"><Input value={form.marcaEntra} onChange={v=>set("marcaEntra",v)}/></Field><Field label="Modelo"><Input value={form.modeloEntra} onChange={v=>set("modeloEntra",v)}/></Field><Field label="Propiedad"><Select value={form.propiedadEntra} onChange={v=>set("propiedadEntra",v)}><option>DELTA</option><option>ALQUILADO</option><option>OTRO</option></Select></Field><Field label="Interno"><Input value={form.internoEntra} onChange={v=>set("internoEntra",v.toUpperCase())}/></Field><Field label="Horómetro"><Input type="number" value={form.horometroEntra} onChange={v=>set("horometroEntra",v)}/></Field></div></div>}
 <Field label="Observación"><Input value={form.observacion} onChange={v=>set("observacion",v)} placeholder="Opcional"/></Field>{(msg||error)&&<div style={{fontSize:12,fontWeight:800,color:msg.includes("correctamente")?C.green:C.red}}>{msg||"No se pudo sincronizar el historial; se conserva la pantalla disponible."}</div>}<div style={{display:"flex",justifyContent:"flex-end"}}><button onClick={save} disabled={saving} style={{...actionStyle,opacity:saving?.6:1}}>{saving?"Guardando...":"Guardar movimiento"}</button></div></div>
 <div style={{background:"rgba(24,24,24,.94)",border:`1px solid ${C.border}`,borderRadius:12,overflow:"hidden"}}><div style={{padding:"12px 14px",fontWeight:900,color:C.text}}>Últimos 100 movimientos</div><div style={{overflowX:"auto",maxHeight:420}}><table style={{width:"100%",borderCollapse:"collapse",fontSize:11}}><thead><tr>{["Fecha","Interno","Equipo","Origen","Destino","Interno destino","Motivo","Usuario"].map(h=><th key={h} style={{textAlign:"left",padding:"9px 10px",borderTop:`1px solid ${C.border}`,borderBottom:`1px solid ${C.border}`,color:C.textMuted,background:"#151515"}}>{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={r.id||i}><td style={{padding:9,borderBottom:`1px solid ${C.border}55`}}>{String(r.fechaHora||"").slice(0,10)}</td><td style={{padding:9,borderBottom:`1px solid ${C.border}55`,color:C.purple,fontWeight:800}}>{r.interno}</td><td style={{padding:9,borderBottom:`1px solid ${C.border}55`}}>{r.equipo||"—"}</td><td style={{padding:9,borderBottom:`1px solid ${C.border}55`}}>{r.proyectoOrigen||"—"}</td><td style={{padding:9,borderBottom:`1px solid ${C.border}55`}}>{r.proyectoDestino||"—"}</td><td style={{padding:9,borderBottom:`1px solid ${C.border}55`}}>{r.internoDestino||"—"}</td><td style={{padding:9,borderBottom:`1px solid ${C.border}55`}}>{r.motivo||"—"}</td><td style={{padding:9,borderBottom:`1px solid ${C.border}55`}}>{r.usuario||"—"}</td></tr>)}{!rows.length&&<tr><td colSpan={8} style={{padding:20,textAlign:"center",color:C.textMuted}}>Sin movimientos registrados</td></tr>}</tbody></table></div></div></div>;
}
