/** DELTA MINING - Supabase -> Google Sheets (Movimiento de equipos) */
const DM_TALLER_SYNC={headers:["ID","FECHA_HORA","TIPO","EQUIPO","MARCA","MODELO","PROPIEDAD","INTERNO_ORIGEN","HOROMETRO","PROYECTO_ORIGEN","PROYECTO_DESTINO","INTERNO_DESTINO","INTERNO_ENTRA","EQUIPO_ENTRA","MARCA_ENTRA","MODELO_ENTRA","PROPIEDAD_ENTRA","HOROMETRO_ENTRA","MOTIVO","OBSERVACION","USUARIO","ESTADO"],sheets:{SUBIDA:"MOVIMIENTOS_SUBIDAS",BAJA:"MOVIMIENTOS_BAJADAS",MOVILIZACION:"MOVIMIENTOS_MOVILIZACIONES",CAMBIO_EQUIPO:"MOVIMIENTOS_CAMBIO_EQUIPO"}};
function instalarTriggerMovimientosSupabase(){eliminarTriggersMovimientosSupabase();ScriptApp.newTrigger("sincronizarMovimientosSupabase").timeBased().everyMinutes(1).create();sincronizarMovimientosSupabase();}
function eliminarTriggersMovimientosSupabase(){ScriptApp.getProjectTriggers().forEach(t=>{if(t.getHandlerFunction()==="sincronizarMovimientosSupabase")ScriptApp.deleteTrigger(t);});}
function sincronizarMovimientosSupabase(){const lock=LockService.getScriptLock();if(!lock.tryLock(25000))return;try{const ss=SpreadsheetApp.getActiveSpreadsheet();const snap=dmObtenerMovimientosDesdeSupabase_();const rows=Array.isArray(snap.data)?snap.data:[];const groups={SUBIDA:[],BAJA:[],MOVILIZACION:[],CAMBIO_EQUIPO:[]};rows.forEach(r=>{const t=String(r.TIPO||r.tipo||"").trim().toUpperCase();if(groups[t])groups[t].push(r);});Object.keys(DM_TALLER_SYNC.sheets).forEach(t=>dmSincronizarHojaMovimiento_(ss,DM_TALLER_SYNC.sheets[t],t,groups[t]));}finally{lock.releaseLock();}}
function dmObtenerMovimientosDesdeSupabase_(){const p=PropertiesService.getScriptProperties(),base=String(p.getProperty("SUPABASE_URL")||"").replace(/\/+$/,"").trim(),key=String(p.getProperty("SUPABASE_KEY")||"").trim();if(!base||!key)throw new Error("Configurá SUPABASE_URL y SUPABASE_KEY en Propiedades del script.");const res=UrlFetchApp.fetch(base+"/rest/v1/rpc/app_taller_movements_snapshot",{method:"post",contentType:"application/json",headers:{apikey:key,Authorization:"Bearer "+key},payload:JSON.stringify({p_type:null,p_active_only:true}),muteHttpExceptions:true});if(res.getResponseCode()<200||res.getResponseCode()>=300)throw new Error("Supabase HTTP "+res.getResponseCode()+": "+res.getContentText());return JSON.parse(res.getContentText());}
function dmSincronizarHojaMovimiento_(ss,name,type,rows){let sh=ss.getSheetByName(name);if(!sh)sh=ss.insertSheet(name);dmAsegurarEncabezados_(sh);const data=(rows||[]).map(dmNormalizarMovimiento_).filter(r=>r.TIPO===type).sort((a,b)=>dmDateMs_(a.FECHA_HORA)-dmDateMs_(b.FECHA_HORA)).map(r=>[r.ID,dmFechaSheets_(r.FECHA_HORA),r.TIPO,r.EQUIPO,r.MARCA,r.MODELO,r.PROPIEDAD,r.INTERNO_ORIGEN,dmNumber_(r.HOROMETRO),r.PROYECTO_ORIGEN,r.PROYECTO_DESTINO,r.INTERNO_DESTINO,r.INTERNO_ENTRA,r.EQUIPO_ENTRA,r.MARCA_ENTRA,r.MODELO_ENTRA,r.PROPIEDAD_ENTRA,dmNumber_(r.HOROMETRO_ENTRA),r.MOTIVO,r.OBSERVACION,r.USUARIO,r.ESTADO||"ACTIVO"]);const props=PropertiesService.getScriptProperties(),hk="DM_TALLER_HASH_"+type,hash=dmHash_(JSON.stringify(data));if(hash===props.getProperty(hk))return;const last=Math.max(sh.getLastRow(),1);if(last>1)sh.getRange(2,1,last-1,DM_TALLER_SYNC.headers.length).clearContent();if(data.length){sh.getRange(2,1,data.length,data[0].length).setValues(data);sh.getRange(2,2,data.length,1).setNumberFormat("dd/MM/yyyy HH:mm:ss");sh.getRange(2,9,data.length,1).setNumberFormat("0.##");sh.getRange(2,18,data.length,1).setNumberFormat("0.##");}props.setProperty(hk,hash);}
function dmAsegurarEncabezados_(sh){const n=DM_TALLER_SYNC.headers.length;if(sh.getMaxColumns()<n)sh.insertColumnsAfter(sh.getMaxColumns(),n-sh.getMaxColumns());const cur=sh.getRange(1,1,1,n).getDisplayValues()[0];if(DM_TALLER_SYNC.headers.some((h,i)=>String(cur[i]||"").trim()!==h))sh.getRange(1,1,1,n).setValues([DM_TALLER_SYNC.headers]);}
function dmNormalizarMovimiento_(r){const t=v=>v==null?"":String(v).trim();return{ID:t(r.ID||r.id),FECHA_HORA:r.FECHA_HORA||r.fechaHora||"",TIPO:t(r.TIPO||r.tipo).toUpperCase(),EQUIPO:t(r.EQUIPO||r.equipo),MARCA:t(r.MARCA||r.marca),MODELO:t(r.MODELO||r.modelo),PROPIEDAD:t(r.PROPIEDAD||r.propiedad),INTERNO_ORIGEN:t(r.INTERNO_ORIGEN||r.interno||r.internoOrigen),HOROMETRO:r.HOROMETRO??r.horometro??0,PROYECTO_ORIGEN:t(r.PROYECTO_ORIGEN||r.proyectoOrigen),PROYECTO_DESTINO:t(r.PROYECTO_DESTINO||r.proyectoDestino),INTERNO_DESTINO:t(r.INTERNO_DESTINO||r.internoDestino),INTERNO_ENTRA:t(r.INTERNO_ENTRA||r.internoEntra),EQUIPO_ENTRA:t(r.EQUIPO_ENTRA||r.equipoEntra),MARCA_ENTRA:t(r.MARCA_ENTRA||r.marcaEntra),MODELO_ENTRA:t(r.MODELO_ENTRA||r.modeloEntra),PROPIEDAD_ENTRA:t(r.PROPIEDAD_ENTRA||r.propiedadEntra),HOROMETRO_ENTRA:r.HOROMETRO_ENTRA??r.horometroEntra??0,MOTIVO:t(r.MOTIVO||r.motivo),OBSERVACION:t(r.OBSERVACION||r.observacion),USUARIO:t(r.USUARIO||r.usuario),ESTADO:t(r.ESTADO||r.estado||"ACTIVO")};}
function dmFechaSheets_(v){if(!v)return"";if(Object.prototype.toString.call(v)==="[object Date]")return v;const d=new Date(String(v));return isNaN(d.getTime())?String(v):d;}
function dmDateMs_(v){const d=dmFechaSheets_(v);return d instanceof Date?d.getTime():0;}
function dmNumber_(v){if(v===""||v==null)return"";const n=Number(v);return isFinite(n)?n:"";}
function dmHash_(text){return Utilities.computeDigest(Utilities.DigestAlgorithm.SHA_256,text,Utilities.Charset.UTF_8).map(b=>("0"+((b<0?b+256:b).toString(16))).slice(-2)).join("");}
